/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type IAccountMeta,
  type IAccountSignerMeta,
  type IInstruction,
  type IInstructionWithAccounts,
  type IInstructionWithData,
  type ReadonlyAccount,
  type ReadonlySignerAccount,
  type TransactionSigner,
  type WritableAccount,
} from '@solana/web3.js';
import { JITO_WEIGHT_TABLE_PROGRAM_ADDRESS } from '../programs';
import { getAccountMetaFactory, type ResolvedAccount } from '../shared';

export const UPDATE_WEIGHT_TABLE_DISCRIMINATOR = 1;

export function getUpdateWeightTableDiscriminatorBytes() {
  return getU8Encoder().encode(UPDATE_WEIGHT_TABLE_DISCRIMINATOR);
}

export type UpdateWeightTableInstruction<
  TProgram extends string = typeof JITO_WEIGHT_TABLE_PROGRAM_ADDRESS,
  TAccountNcn extends string | IAccountMeta<string> = string,
  TAccountWeightTable extends string | IAccountMeta<string> = string,
  TAccountWeightTableAdmin extends string | IAccountMeta<string> = string,
  TAccountRestakingProgramId extends string | IAccountMeta<string> = string,
  TRemainingAccounts extends readonly IAccountMeta<string>[] = [],
> = IInstruction<TProgram> &
  IInstructionWithData<Uint8Array> &
  IInstructionWithAccounts<
    [
      TAccountNcn extends string ? ReadonlyAccount<TAccountNcn> : TAccountNcn,
      TAccountWeightTable extends string
        ? WritableAccount<TAccountWeightTable>
        : TAccountWeightTable,
      TAccountWeightTableAdmin extends string
        ? ReadonlySignerAccount<TAccountWeightTableAdmin> &
            IAccountSignerMeta<TAccountWeightTableAdmin>
        : TAccountWeightTableAdmin,
      TAccountRestakingProgramId extends string
        ? ReadonlyAccount<TAccountRestakingProgramId>
        : TAccountRestakingProgramId,
      ...TRemainingAccounts,
    ]
  >;

export type UpdateWeightTableInstructionData = {
  discriminator: number;
  ncnEpoch: bigint;
  weightNumerator: bigint;
  weightDenominator: bigint;
};

export type UpdateWeightTableInstructionDataArgs = {
  ncnEpoch: number | bigint;
  weightNumerator: number | bigint;
  weightDenominator: number | bigint;
};

export function getUpdateWeightTableInstructionDataEncoder(): Encoder<UpdateWeightTableInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ['discriminator', getU8Encoder()],
      ['ncnEpoch', getU64Encoder()],
      ['weightNumerator', getU64Encoder()],
      ['weightDenominator', getU64Encoder()],
    ]),
    (value) => ({ ...value, discriminator: UPDATE_WEIGHT_TABLE_DISCRIMINATOR })
  );
}

export function getUpdateWeightTableInstructionDataDecoder(): Decoder<UpdateWeightTableInstructionData> {
  return getStructDecoder([
    ['discriminator', getU8Decoder()],
    ['ncnEpoch', getU64Decoder()],
    ['weightNumerator', getU64Decoder()],
    ['weightDenominator', getU64Decoder()],
  ]);
}

export function getUpdateWeightTableInstructionDataCodec(): Codec<
  UpdateWeightTableInstructionDataArgs,
  UpdateWeightTableInstructionData
> {
  return combineCodec(
    getUpdateWeightTableInstructionDataEncoder(),
    getUpdateWeightTableInstructionDataDecoder()
  );
}

export type UpdateWeightTableInput<
  TAccountNcn extends string = string,
  TAccountWeightTable extends string = string,
  TAccountWeightTableAdmin extends string = string,
  TAccountRestakingProgramId extends string = string,
> = {
  ncn: Address<TAccountNcn>;
  weightTable: Address<TAccountWeightTable>;
  weightTableAdmin: TransactionSigner<TAccountWeightTableAdmin>;
  restakingProgramId: Address<TAccountRestakingProgramId>;
  ncnEpoch: UpdateWeightTableInstructionDataArgs['ncnEpoch'];
  weightNumerator: UpdateWeightTableInstructionDataArgs['weightNumerator'];
  weightDenominator: UpdateWeightTableInstructionDataArgs['weightDenominator'];
};

export function getUpdateWeightTableInstruction<
  TAccountNcn extends string,
  TAccountWeightTable extends string,
  TAccountWeightTableAdmin extends string,
  TAccountRestakingProgramId extends string,
  TProgramAddress extends Address = typeof JITO_WEIGHT_TABLE_PROGRAM_ADDRESS,
>(
  input: UpdateWeightTableInput<
    TAccountNcn,
    TAccountWeightTable,
    TAccountWeightTableAdmin,
    TAccountRestakingProgramId
  >,
  config?: { programAddress?: TProgramAddress }
): UpdateWeightTableInstruction<
  TProgramAddress,
  TAccountNcn,
  TAccountWeightTable,
  TAccountWeightTableAdmin,
  TAccountRestakingProgramId
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? JITO_WEIGHT_TABLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    ncn: { value: input.ncn ?? null, isWritable: false },
    weightTable: { value: input.weightTable ?? null, isWritable: true },
    weightTableAdmin: {
      value: input.weightTableAdmin ?? null,
      isWritable: false,
    },
    restakingProgramId: {
      value: input.restakingProgramId ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, 'programId');
  const instruction = {
    accounts: [
      getAccountMeta(accounts.ncn),
      getAccountMeta(accounts.weightTable),
      getAccountMeta(accounts.weightTableAdmin),
      getAccountMeta(accounts.restakingProgramId),
    ],
    programAddress,
    data: getUpdateWeightTableInstructionDataEncoder().encode(
      args as UpdateWeightTableInstructionDataArgs
    ),
  } as UpdateWeightTableInstruction<
    TProgramAddress,
    TAccountNcn,
    TAccountWeightTable,
    TAccountWeightTableAdmin,
    TAccountRestakingProgramId
  >;

  return instruction;
}

export type ParsedUpdateWeightTableInstruction<
  TProgram extends string = typeof JITO_WEIGHT_TABLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly IAccountMeta[] = readonly IAccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    ncn: TAccountMetas[0];
    weightTable: TAccountMetas[1];
    weightTableAdmin: TAccountMetas[2];
    restakingProgramId: TAccountMetas[3];
  };
  data: UpdateWeightTableInstructionData;
};

export function parseUpdateWeightTableInstruction<
  TProgram extends string,
  TAccountMetas extends readonly IAccountMeta[],
>(
  instruction: IInstruction<TProgram> &
    IInstructionWithAccounts<TAccountMetas> &
    IInstructionWithData<Uint8Array>
): ParsedUpdateWeightTableInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error('Not enough accounts');
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = instruction.accounts![accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      ncn: getNextAccount(),
      weightTable: getNextAccount(),
      weightTableAdmin: getNextAccount(),
      restakingProgramId: getNextAccount(),
    },
    data: getUpdateWeightTableInstructionDataDecoder().decode(instruction.data),
  };
}
