/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  containsBytes,
  getU8Encoder,
  type Address,
  type ReadonlyUint8Array,
} from '@solana/web3.js';
import {
  type ParsedFinalizeWeightTableInstruction,
  type ParsedInitializeWeightTableInstruction,
  type ParsedUpdateWeightTableInstruction,
} from '../instructions';

export const JITO_WEIGHT_TABLE_PROGRAM_ADDRESS =
  'ENHcxLEWQxRyS8VbC7Pb6GKc739vVaBZ2toJvQSL68vM' as Address<'ENHcxLEWQxRyS8VbC7Pb6GKc739vVaBZ2toJvQSL68vM'>;

export enum JitoWeightTableAccount {
  WeightTable,
}

export enum JitoWeightTableInstruction {
  InitializeWeightTable,
  UpdateWeightTable,
  FinalizeWeightTable,
}

export function identifyJitoWeightTableInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array
): JitoWeightTableInstruction {
  const data = 'data' in instruction ? instruction.data : instruction;
  if (containsBytes(data, getU8Encoder().encode(0), 0)) {
    return JitoWeightTableInstruction.InitializeWeightTable;
  }
  if (containsBytes(data, getU8Encoder().encode(1), 0)) {
    return JitoWeightTableInstruction.UpdateWeightTable;
  }
  if (containsBytes(data, getU8Encoder().encode(2), 0)) {
    return JitoWeightTableInstruction.FinalizeWeightTable;
  }
  throw new Error(
    'The provided instruction could not be identified as a jitoWeightTable instruction.'
  );
}

export type ParsedJitoWeightTableInstruction<
  TProgram extends string = 'ENHcxLEWQxRyS8VbC7Pb6GKc739vVaBZ2toJvQSL68vM',
> =
  | ({
      instructionType: JitoWeightTableInstruction.InitializeWeightTable;
    } & ParsedInitializeWeightTableInstruction<TProgram>)
  | ({
      instructionType: JitoWeightTableInstruction.UpdateWeightTable;
    } & ParsedUpdateWeightTableInstruction<TProgram>)
  | ({
      instructionType: JitoWeightTableInstruction.FinalizeWeightTable;
    } & ParsedFinalizeWeightTableInstruction<TProgram>);
