/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
} from '@solana/web3.js';
import {
  getWeightEntryDecoder,
  getWeightEntryEncoder,
  type WeightEntry,
  type WeightEntryArgs,
} from '../types';

export type WeightTable = {
  discriminator: bigint;
  ncn: Address;
  ncnEpoch: bigint;
  slotCreated: bigint;
  slotFinalized: bigint;
  bump: number;
  reserved: Array<number>;
  table: Array<WeightEntry>;
};

export type WeightTableArgs = {
  discriminator: number | bigint;
  ncn: Address;
  ncnEpoch: number | bigint;
  slotCreated: number | bigint;
  slotFinalized: number | bigint;
  bump: number;
  reserved: Array<number>;
  table: Array<WeightEntryArgs>;
};

export function getWeightTableEncoder(): Encoder<WeightTableArgs> {
  return getStructEncoder([
    ['discriminator', getU64Encoder()],
    ['ncn', getAddressEncoder()],
    ['ncnEpoch', getU64Encoder()],
    ['slotCreated', getU64Encoder()],
    ['slotFinalized', getU64Encoder()],
    ['bump', getU8Encoder()],
    ['reserved', getArrayEncoder(getU8Encoder(), { size: 128 })],
    ['table', getArrayEncoder(getWeightEntryEncoder(), { size: 32 })],
  ]);
}

export function getWeightTableDecoder(): Decoder<WeightTable> {
  return getStructDecoder([
    ['discriminator', getU64Decoder()],
    ['ncn', getAddressDecoder()],
    ['ncnEpoch', getU64Decoder()],
    ['slotCreated', getU64Decoder()],
    ['slotFinalized', getU64Decoder()],
    ['bump', getU8Decoder()],
    ['reserved', getArrayDecoder(getU8Decoder(), { size: 128 })],
    ['table', getArrayDecoder(getWeightEntryDecoder(), { size: 32 })],
  ]);
}

export function getWeightTableCodec(): Codec<WeightTableArgs, WeightTable> {
  return combineCodec(getWeightTableEncoder(), getWeightTableDecoder());
}

export function decodeWeightTable<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>
): Account<WeightTable, TAddress>;
export function decodeWeightTable<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>
): MaybeAccount<WeightTable, TAddress>;
export function decodeWeightTable<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>
): Account<WeightTable, TAddress> | MaybeAccount<WeightTable, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getWeightTableDecoder()
  );
}

export async function fetchWeightTable<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<Account<WeightTable, TAddress>> {
  const maybeAccount = await fetchMaybeWeightTable(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeWeightTable<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig
): Promise<MaybeAccount<WeightTable, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeWeightTable(maybeAccount);
}

export async function fetchAllWeightTable(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<Account<WeightTable>[]> {
  const maybeAccounts = await fetchAllMaybeWeightTable(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeWeightTable(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig
): Promise<MaybeAccount<WeightTable>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeWeightTable(maybeAccount));
}
