/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';

export type Weight = { numerator: bigint; denominator: bigint };

export type WeightArgs = {
  numerator: number | bigint;
  denominator: number | bigint;
};

export function getWeightEncoder(): Encoder<WeightArgs> {
  return getStructEncoder([
    ['numerator', getU64Encoder()],
    ['denominator', getU64Encoder()],
  ]);
}

export function getWeightDecoder(): Decoder<Weight> {
  return getStructDecoder([
    ['numerator', getU64Decoder()],
    ['denominator', getU64Decoder()],
  ]);
}

export function getWeightCodec(): Codec<WeightArgs, Weight> {
  return combineCodec(getWeightEncoder(), getWeightDecoder());
}
