/**
 * This code was AUTOGENERATED using the kinobi library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun kinobi to update it.
 *
 * @see https://github.com/kinobi-so/kinobi
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/web3.js';
import {
  getWeightDecoder,
  getWeightEncoder,
  type Weight,
  type WeightArgs,
} from '.';

export type WeightEntry = { mint: Address; weight: Weight };

export type WeightEntryArgs = { mint: Address; weight: WeightArgs };

export function getWeightEntryEncoder(): Encoder<WeightEntryArgs> {
  return getStructEncoder([
    ['mint', getAddressEncoder()],
    ['weight', getWeightEncoder()],
  ]);
}

export function getWeightEntryDecoder(): Decoder<WeightEntry> {
  return getStructDecoder([
    ['mint', getAddressDecoder()],
    ['weight', getWeightDecoder()],
  ]);
}

export function getWeightEntryCodec(): Codec<WeightEntryArgs, WeightEntry> {
  return combineCodec(getWeightEntryEncoder(), getWeightEntryDecoder());
}
